#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
#this file used in our own systemd unit file: cci-network.service.
#contents as follows will be automatically executed after system reboot.

# export ENV
. /etc/profile.d/compass.sh

$CCI_SRC/sparrow/2-network/br0
$CCI_SRC/sparrow/2-network/iptables
$CCI_SRC/sparrow/2-network/nfs
$CCI_SRC/sparrow/2-network/cifs

# --restart=always option is not absolutely reliable
# container need to start its dependences firstly.
$CCI_SRC/sparrow/4-docker/buildall reboot
