#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

cp $(dirname $0)/cci-network.service /etc/systemd/system
systemctl daemon-reload
systemctl enable cci-network.service
systemctl start  cci-network.service
