#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

: ${dc_hostname:=dc-8g}
: ${dc_count:=10}

run_multi_docker()
{
	[ "$prepare_testboxes" = "false" ] && return 0

	nohup $CCI_SRC/providers/multi-docker -n $dc_hostname -c $dc_count -q $dc_hostname.$(arch) &
}

run_multi_docker
