#!/usr/bin/env bash

[[ $CCI_SRC ]] || CCI_SRC=/c/cci
[[ $LKP_SRC ]] || LKP_SRC=/c/lkp-tests

CODE_DIR=/c/cci/src
COMPILE_DIR=/c/cci/compile

if [ ! $1 ]; then
  echo "Usage: $0 [scheduler | taskqueue ...]"
  exit 1
fi

DIR=$(realpath $1)
if [ ! -d $DIR ]; then
  echo "Service dir $DIR not exists"
  exit 1
fi
service=${DIR##*/}

cmd=(
  docker run
  --rm
  -e LKP_SRC=/c/lkp-tests
  -e CRYSTAL_PATH="lib:/usr/share/crystal/app/lib:/usr/lib/crystal/shards:/usr/lib/crystal/core:/c/lkp-tests/lib:$CODE_DIR"
  -it
  -u $UID
  -v $LKP_SRC:/c/lkp-tests
  -v $CCI_SRC/src:$CODE_DIR
  -v $DIR:$COMPILE_DIR
  -w $COMPILE_DIR
  alpine:scheduler-dev
  sh -c "crystal build $CODE_DIR/$service.cr"
)

"${cmd[@]}"
