#!/bin/bash 
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

DIR="$(pwd)"
os_name="$(echo $DIR | awk -F "/" '{print $(NF - 2)}')"
os_version="$(echo $DIR | awk -F "/" '{print $NF}')"
docker_url="https://repo.openeuler.org/openEuler-${os_version}/docker_img/aarch64/openEuler-docker.aarch64.tar.xz"
docker_tar_file="openEuler-${os_version}-docker.aarch64.tar.xz"
image=$(echo "${os_name}-${os_version,,}")
IMAGE_NAME="${os_name}-${os_version}-$(date +"%Y%m%d").cgz"

export_root_passwd() 
{
	local root_pwd_file="$HOME/.config/compass-ci/rootfs-passwd"
	[ -f "$root_pwd_file" ] || {
		echo "[INFO] Please set the password file."
		echo "$HOME/.config/compass-ci/rootfs-passwd"
		exit 1
        }

        export ROOT_PASSWD=$(cat "$root_pwd_file")
}

load_docker_image()
{
	if [[ "$os_version" == '20.09' || "$os_version" == '20.03-LTS' ]]; then
		[ -f "$HOME/$docker_tar_file" ] || wget -O "$HOME/$docker_tar_file" "$docker_url"
	fi

	docker load -i "$HOME/$docker_tar_file"

	if [ $? -eq 0 ]; then
		echo "finish downloading image"
	else
		echo "[ERROR] Pull docker image failed."
		exit 1
	fi
}

cp_image_to_host()
{
	docker cp -a init_docker:/tmp/${IMAGE_NAME} $HOME/ 
	echo "result: $(ls $HOME/${IMAGE_NAME})"
}
