#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require 'set'
require_relative '../defconfig.rb'

names = Set.new %w[
  TASKQUEUE_HOST
  TASKQUEUE_PORT
]

defaults = relevant_defaults(names)
env = docker_env(defaults)

DEFAULT_LKP = '/c/lkp-tests'
DEFAULT_CCI = '/c/compass-ci'
DEFAULT_CONFIG_DIR = '/etc/compass-ci/defaults'
docker_rm 'delimiter'

cmd = %w[
  docker run
  --name delimiter
  --restart=always
  -d
] + env + %W[
  -e LKP_SRC=#{DEFAULT_LKP}
  -e CCI_SRC=#{DEFAULT_CCI}
  -v #{ENV['LKP_SRC']}:#{DEFAULT_LKP}
  -v #{ENV['CCI_SRC']}:#{DEFAULT_CCI}
  -v #{DEFAULT_CONFIG_DIR}:#{DEFAULT_CONFIG_DIR}:ro
  -v /etc/localtime:/etc/localtime:ro
  -v /etc/compass-ci/register:/etc/compass-ci/register:ro
  delimiter
]

cmd += ['sh', '-c', 'umask 002 && ./delimiter']

system(*cmd)
