#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# frozen_string_literal: true

require 'set'
require_relative '../defconfig.rb'

names = Set.new %w[
  ES_HOST
  ES_PORT
  MAIL_HOST
  MAIL_PORT
  MONITOR_HOST
  MONITOR_PORT
  TASKQUEUE_HOST
  TASKQUEUE_PORT
  GIT_MIRROR_HOST
]

defaults = relevant_defaults(names)
env = docker_env(defaults)

DEFAULT_LKP = '/c/lkp-tests'
DEFAULT_CCI = '/c/compass-ci'
docker_rm 'delimiter'

cmd = %w[
  docker run
  --name delimiter
  --restart=always
  -d
] + env + %W[
  -e LKP_SRC=#{DEFAULT_LKP}
  -e CCI_SRC=#{DEFAULT_CCI}
  -v #{ENV['LKP_SRC']}:#{DEFAULT_LKP}
  -v /etc/localtime:/etc/localtime:ro
  -v #{ENV['CCI_SRC']}:#{DEFAULT_CCI}
  -w #{DEFAULT_CCI}/src
  delimiter
]

cmd += ['sh', '-c', 'umask 002 && ruby ./delimiter.rb']

system(*cmd)
