#!/bin/bash

# To adapt packages between distributions, use Debian as the default distribution.
# The adaptation file is in dir $LKP_SRC/distro/adaptation, default file is $1,
# if not found, get centos then. 

get_packages()                                              
{                                                      
	distro_file="$LKP_SRC/distro/adaptation/$1"
	while read -r line
	do
		pack=$(echo "$line" | awk -F ":" '{print $2}') 
		[ -n "$pack" ] || {
			pack=$(echo "$line" | awk -F ":" '{print $1}')
		}
		packages+=" $pack"
	done < "$distro_file"
	echo "$packages"
}

# adaptation file contain packages map from debian to distro
distro=$1

[ -f "$LKP_SRC/distro/adaptation/$distro" ] && {
	packages=$(get_packages "$distro" | sort | uniq)
}

[ -z "$distro" ] && {
	 packages=$(get_packages centos | sort | uniq)
}

echo "$packages"
