#!/bin/bash

[ -d "$1" -a -n "$2" ] || {
	cat << 'EOF'
	Example usage:
	1> ./run /os/centos/aarch64/76 pack1 pack2 ...
	2> ./run /os/centos/aarch64/76 $(show-depends-packages $distro)
	distro is an adaption file contain packages mapping from debian to other os,
	the whole path is '$LKP_SRC/distro/adaptation/$distro', default $distro is centos
EOF
	exit
}

rootdir=$1
packages="${*:2}"

cmd=(
	docker run
	--rm
	-it
	-v "$rootdir":/mnt/root
	addsoftware:auto
	yum install -y --skip-broken --installroot=/mnt/root $packages
)

os=$(echo "$rootdir" | awk -F '/' '{print $3}')
echo "rootdir=$rootdir" | tee install-$os.log 
"${cmd[@]}" | tee -a install-$os.log
