#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

[ -d "$1" -a -n "$2" ] || {
	cat << 'EOF'
	Example usage:
	1> ./run /os/centos/aarch64/76 pack1 pack2 ...
	2> ./run /os/centos/aarch64/76 $(show-depends-packages $distro)
	distro is an adaption file contain packages mapping from debian to other os,
	the whole path is '$LKP_SRC/distro/adaptation/$distro', default $distro is centos
EOF
	exit
}

rootdir=$1
packages="${*:2}"

cmd=(
	docker run
	--rm
	-v "$rootdir":/mnt/root
	addsoftware:auto
	yum install -y --skip-broken --installroot=/mnt/root $packages
)

osinfo=(${rootdir//\// })
os=${osinfo[1]}
arch=${osinfo[2]}
version=${osinfo[3]}
echo "rootdir=$rootdir" | tee install-$os-$arch-$version.log 
"${cmd[@]}" | tee -a install-$os-$arch-$version.log
