#!/bin/sh
# SPDX-License-Identifier: MulanPSL-2.0+

. ../defconfig.sh

docker_skip_rebuild "centos:web-backend"

# TODO: cbs has been retired; keep this legacy repo list for now and clean it up
# after the remaining container build inputs are audited.
repos=("cbs" "lkp-tests")
for repo in "${repos[@]}"
do
	download_repo ${repo}
done

docker build -t centos:web-backend .

push_image_remote "debian:web-backend"
