#!/bin/bash
set -e

CURRENT_PATH=$(dirname `readlink -f $0`)
PROJECT_PATH=$(dirname $(dirname $CURRENT_PATH))
PROJECT_NAME=$(basename "$PROJECT_PATH")

if [ -d "$CURRENT_PATH/$PROJECT_NAME" ]; then
	        rm -rf $CURRENT_PATH/$PROJECT_NAME
fi

if [ -d "$CURRENT_PATH/lkp-tests" ]; then
	        rm -rf $CURRENT_PATH/lkp-tests
fi

git clone -b $CCI_BRANCH --single-branch --depth=1 https://gitee.com/openeuler/$PROJECT_NAME
git clone --depth=1 https://gitee.com/compass-ci/lkp-tests
