#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+


[[ $CCI_SRC ]] || CCI_SRC=/c/compass-ci
[[ $LKP_SRC ]] || LKP_SRC=/c/lkp-tests
[[ $UPSTREAM_REPOS_PATH ]] || UPSTREAM_REPOS_PATH=/c/upstream-repos

. $CCI_SRC/container/defconfig.sh
docker_rm web-backend

load_cci_defaults
[[ $SRV_HTTP_RESULT_HOST ]] || SRV_HTTP_RESULT_HOST=$(curl ip.sb)
[[ $SRV_HTTP_RESULT_PORT ]] || SRV_HTTP_RESULT_PORT=11300

cmd=(
	docker run
	--name web-backend
	--restart=always
	-d
	-p 32767:32767

	-e ES_PORT=9200
	-e SRV_HTTP_RESULT_HOST=$SRV_HTTP_RESULT_HOST
	-e SRV_HTTP_RESULT_PORT=$SRV_HTTP_RESULT_PORT
	-e CCI_SRC=/c/compass-ci
	-e LKP_SRC=/c/lkp-tests
	-e UPSTREAM_REPOS_PATH=/c/upstream-repos

	-v $CCI_SRC:/c/compass-ci
	-v $LKP_SRC:/c/lkp-tests
	-v $UPSTREAM_REPOS_PATH:/c/upstream-repos

	--log-opt mode=non-blocking
	--log-opt max-buffer-size=4m

	debian:web-backend
)

"${cmd[@]}"
