# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

FROM debian
MAINTAINER shdluan@163.com
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y ruby-mail ruby-json ruby-sinatra
