#!/bin/sh
# SPDX-License-Identifier: MulanPSL-2.0+

cmd=(
	docker run
	--restart=always
	--name=send-mail
	-u nobody
	-d
	-p 8101:8101
	send-mail
)

"${cmd[@]}"

cat<<EOF
port: 8101
---
data='{
"subject": "mail subject",
"to": "email_to_addr",
"body": "email message"
}'

or

data="
subject: mail subject
to: email_to_addr
body: email message"

curl -XPOST 'localhost:8101/send_mail_yaml' -d "$data"

---
data="
To: mail_address
Subject: mail_subject

mail_msg_line1
mail_msg_line2
...
"

curl -XPOST 'localhost:8101/send_mail_text' -d "$data"
EOF
