#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

cmd=(
	docker run
	--restart=always
	--name=send-mail
	-u nobody
	-d
	-p 11311:11311
	-v /etc/localtime:/etc/localtime:ro
	send-mail
)

"${cmd[@]}"

cat<<EOF
port: 11311
---
data='{
"from": "email_from_addr" # default: team@crystal.ci
"subject": "email subject",
"to": "email_to_addr",
"body": "email message"
}'

or

data="
from: email_from_addr # default: team@crystal.ci
subject: email subject
to: email_to_addr
body: email message"

when compass-ci:
	curl -XPOST 'localhost:11311/send_mail_yaml' -d "$data"
when other server:
	curl -XPOST '124.90.34.227:11311/send_mail_yaml' -d "$data"

---
data="
From: email_from_addr # default: team@crystal.ci
To: email_to_addr
Subject: email_subject

mail_msg_line1
mail_msg_line2
...
"

when compass-ci:
	curl -XPOST 'localhost:11311/send_mail_text' -d "$data"
when other server:
	curl -XPOST '124.90.34.227:11311/send_mail_text' -d "$data"
EOF
