#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
. ../defconfig.sh

load_cci_defaults

cmd=(
	docker run
	--restart=always
#	--name os-http
	-p ${OS_HTTP_PORT:-8000}:80
	-v /srv/os:/usr/share/nginx/html/os:ro
	-v /etc/localtime:/etc/localtime:ro
	-d
	os-http
)

"${cmd[@]}"
