#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
. ../defconfig.sh

load_cci_defaults

cmd=(
	docker run
	--restart=always
#	--name os-http
	-p ${OS_HTTP_PORT:-8000}:80
	-v /srv/os:/usr/share/nginx/html/os:ro
	-d
	os-http
)

"${cmd[@]}"
