#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

# docker_skip_rebuild "alpine:crystal-compiler"

podman build -t alpine:crystal-compiler .
