#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

DIR=$(dirname $(realpath $0))
sudo ln -sf $DIR/run /usr/local/bin/crystal
