#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh
. $CCI_SRC/container/srv-http/docker_run.sh
docker_rm compass-ci-web

cmd=(
        docker run
        --restart=always
        --name compass-ci-web
	-e LISTEN_PORT=20030
        -p 20030:20030
        -v /etc/localtime:/etc/localtime:ro
	$(mount_ssl)
	-d
        compass-ci-web
)

"${cmd[@]}"
