# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

FROM nginx:1.20.0-alpine

MAINTAINER Li Yuanchao <lyc163mail@163.com>

COPY html /etc/nginx/html
COPY nginx.conf /etc/nginx/
