#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

CONTAINER_PATH="$CCI_SRC/container"
export action=$1

source ${CCI_SRC}/lib/log.sh

build_depends()
{
	local container=$1

	for dep in $(cat $container/*-depends 2> /dev/null)
	do
		build_depends $CONTAINER_PATH/$dep &
	done
	wait

	do_one $container
}

do_one()
{
	local container=$1
	local container_name=$(basename $container)
	lockfile-create -q --use-pid --retry 100 --lock-name "$container_name".lock

	log_info "start build $container."
	mkdir $tmpdir/$container_name 2>/dev/null &&
	(
		cd "$container"
		[ "$container_name" == 'ssh-r' ] && exit
		docker images | grep -wq "$container_name"
		if [ "$?" != 0 ] || [ "$action" != "run-only" ]; then
			[ -x build ] && ./build
			[ -x install ] && ./install
		fi
		[ -x first-run ] && ./first-run
		[ -x start ] && ./start
		[ "$container_name" == 'initrd-lkp' ] && ./run
	)
	log_info "finish build $container."
	lockfile-remove --lock-name "$container_name".lock
}

tmpdir=$(mktemp -d)

for dir in $CONTAINER_PATH/*/
do
	build_depends $dir &
done
wait

rm -fr $tmpdir
