#!/bin/bash

CONTAINER_PATH="$CCI_SRC/container"

build_depends()
{
	local container=$1
	local should_wait=$2

	[ -f "$container/depends" ] && {
		for line in $(<$container/depends)
		do
			build_depends $CONTAINER_PATH/$line block_wait
		done
	}

	if [ -n "$should_wait" ]; then
		do_one $container
	else
		do_one $container &
	fi
}

do_one()
{
	local container=$1
	local container_name=$(basename $container)
	lockfile-create -q --use-pid --retry 100 --lock-name "$container_name".lock
	mkdir $tmpdir/$container_name 2>/dev/null &&
	(
		cd $container
		[ -x build ] && ./build
		[ -x install ] && ./install
		[ -x first-run ] && ./first-run
		[ "$container_name" == 'os-nfs' ] && exit
		[ -x start ] && ./start
	)
	lockfile-remove --lock-name "$container_name".lock
}

tmpdir=$(mktemp -d)

for dir in $CONTAINER_PATH/*/
do
	build_depends $dir
done

wait
rm -fr $tmpdir
