#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_skip_rebuild "openresty:proxy_cache"

[ -d "openresty" ] && rm -rf openresty

git clone http://gitee.com/cuiyili/openresty.git || exit 1

docker build -t openresty:proxy_cache . -f openresty/Dockerfile
