#!/bin/bash

if [ $# -gt 2 ] || [ $# -lt 1 ]; then
  echo "USAGE: $0 id                 # hget for id2content"
  echo "     : $0 queues/your_key id # hget for your key"
  exit 1
fi

if [[ $2 ]]; then
  key_name=$1
  id=$2
else
  key_name=queues/id2content
  id=$1
fi

# use current filename's last string as lua command script
cmd_lua=${0##*_}

redis-cli --eval key_cmd_params.lua $key_name , $cmd_lua $id
