#!/bin/sh
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_skip_rebuild "scheduler-nginx"

docker build --no-cache -t scheduler-nginx .

push_image_remote "scheduler-nginx"
