#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_skip_rebuild "manticore"

# docker build --no-cache -t manticore .
docker pull manticoresearch/manticore

push_image_remote "manticore"
