#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

start_pod

docker_rm manticore

cmd=(
	docker run
	--restart=always
	-d
	# -e EXTRA=1 # disable: too slow startup and unstable
	-e MCL=1 # install Columnar Lib
	--name manticore
	-p 9306:9306
	-p 9308:9308
	-p 9312:9312
	-v /srv/es/manticore:/var/lib/manticore
	manticoresearch/manticore
)

"${cmd[@]}"
