#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

export DEBIAN_FRONTEND=noninteractive

pkgs=(
	vim
	lvm2
	gcc
	g++
	make
	docker.io
	ruby-full
	ruby-dev
	bridge-utils
	qemu
	dmidecode
	lockfile-progs
)

apt-get install -y "${pkgs[@]}"
