#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

export DEBIAN_FRONTEND=noninteractive

pkgs=(
	vim
	lvm2
	gcc
	g++
	make
	docker.io
	ruby-full
	ruby-dev
	dmidecode
	lockfile-progs
	bridge-utils
	busybox
	iproute2
	hostname
	wget
	curl
	qemu-system-aarch64
	qemu-system-x86
	qemu-system-riscv64
	sudo
	iputils
)

apt-get update
apt-get install -y --fix-missing "${pkgs[@]}"
