#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

export DEBIAN_FRONTEND=noninteractive

pkgs=(
	vim
	git
	gcc
	g++
	make
	ruby-full
	ruby-rubygems
	rubygems-integration
	ruby-dev
	ruby-docker-api
	bridge-utils
	qemu-system
	lvm2
	docker.io
	dmidecode
	redis-server
	wget
	busybox
	iproute2
	hostname
	libvirt-daemon-system
	curl
	sudo
	iputils-ping
	libxml2-dev
	libxslt1-dev
	libvirt-dev
	nmap
	expect
	lockfile-progs
)

apt-get update
apt-get --fix-broken install -y
apt-get install -y --fix-missing "${pkgs[@]}"
