#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

[[ $CCI_SRC ]] || CCI_SRC=/c/compass-ci

. $CCI_SRC/lib/check_public_network.sh

pkgs=(
	vim
	git
	gcc
	gcc-c++
	make
	ruby
	rubygems
	ruby-devel
	bridge-utils
	qemu
	lvm2
	docker-engine
	dmidecode
	redis
	wget
	busybox
	iproute
	hostname
	libvirt
	curl
	sudo
	iputils
	libxml2-devel
	libxslt-devel
	libvirt-devel
	nmap
	expect
)

public_network_ok && {
	yum install -y --skip-broken "${pkgs[@]}"
}
