#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+


[[ $CCI_SRC ]] || CCI_SRC=/c/compass-ci

. $CCI_SRC/container/defconfig.sh
docker_rm service-health

cmd=(
	docker run
	--name service-health
	-p 20021:20021
	-d

	--log-opt mode=non-blocking
	--log-opt max-buffer-size=4m

	service-health
)

"${cmd[@]}"
