apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: ems1
spec:
  serviceName: redis
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
      - name: init
        image: redis:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          chown -hR 1090:1090 /var/log/redis;
        volumeMounts:
        - name: log
          mountPath: /var/log/redis
        securityContext:
          runAsUser: 0
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        command:
        - "redis-server"
        args:
        - "/etc/redis.conf"
        - "--protected-mode"
        - "no"
        - "--cluster-announce-ip"
        - "$(POD_IP)"
        envFrom:
        - secretRef:
            name: secrets-env
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: run-redis
          mountPath: /run/redis
        - name: redis
          mountPath: /srv/redis
        - name: log
          mountPath: /var/log/redis
        ports:
        - name: client
          containerPort: 6379
        - name: cluster
          containerPort: 16379
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            memory: 15Gi
          requests:
            memory: 10Mi
        securityContext:
          runAsUser: 1090
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
      dnsPolicy: ClusterFirst
      volumes:
      - name: run-redis
        emptyDir: {}
      - name: log
        hostPath:
          path: /srv/log/redis
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes:
      - "ReadWriteOnce"
      storageClassName: pub-storageclass
      resources:
        requests:
          storage: 50Gi
