#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. '../defconfig.sh'

cmd=(
	docker run
	--name qemu-efi
	debian:qemu-efi
)

"${cmd[@]}"

[ $(arch) == "aarch64" ] && uefi=qemu-efi-aarch64
[ $(arch) == "x86_64" ] && uefi=ovmf

docker cp qemu-efi:/usr/share/$uefi /usr/share/$uefi
docker_rm qemu-efi
