#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2024 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_skip_rebuild "bisect"

load_cci_defaults

docker build -t bisect .

push_image bisect:latest

#rm bisect
