#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2024 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require 'set'
require_relative '../defconfig.rb'

names = Set.new %w[
  ES_HOST
  ES_PORT
  ES_USER
  ES_PASSWORD
]

defaults = relevant_defaults(names)

service_authentication = relevant_service_authentication(names)
defaults.merge!(service_authentication)

env = docker_env(defaults)

# 开发模式配置
# 使用方式：BISECT_DEV_MODE=true ./start
# 开发模式下代码通过 volume 映射，修改后只需 docker restart bisect
DEV_MODE = ENV['BISECT_DEV_MODE'] == 'true'
HOST_CCI_SRC = ENV['HOST_CCI_SRC'] || File.expand_path('~/git/gitee/compass-ci')
HOST_LKP_SRC = ENV['HOST_LKP_SRC'] || File.expand_path('~/git/gitee/lkp-tests')

DEFAULT_LKP = '/c/lkp-tests'
DEFAULT_CCI = '/c/compass-ci'
FLASK_APP = '/c/compass-ci/container/bisect/app/__init__.py'
DEFAULT_CONFIG_DIR = '/etc/compass-ci/defaults'
DEFAULT_USER_CONFIG_DIR = File.expand_path("~/.config/compass-ci/")
DEFAULT_BISECT_CONFIG_DIR = '/home/bisect/.config/compass-ci/'
DEFAULT_CACHE = '/srv/cache'
MANTICORE_HOST='172.17.0.1'
BISECT_WORK_DIR='/c/bisect'
HOST_WORK_DIR='/tmp/'
BISECT_RESULT_DIR='/result/'
HOST_RESULT_DIR='/srv/result'
KERNEL_CI_DIR='/srv/log/kernel_ci'
AUTO_TEST_REPOS_DIR='/srv/git/auto_test_repos'
SUPERVISORD_CONF = File.join(File.dirname(__FILE__), 'config/supervisord.conf')
NOTIFICATION_WEBHOOK_URL = ENV['BISECT_NOTIFICATION_WEBHOOK_URL'] || ''
NOTIFICATION_FEISHU_WEBHOOK_URL = ENV['BISECT_FEISHU_WEBHOOK_URL'] || ''
NOTIFICATION_FEISHU_SECRET = ENV['BISECT_FEISHU_SECRET'] || ''
NOTIFICATION_EMAIL = ENV['BISECT_NOTIFICATION_EMAIL'] || ''
HEAD_VALIDATOR_ENABLED = ENV['BISECT_HEAD_VALIDATOR_ENABLED'] || 'true'
CURRENT_QUERY_HOURS = ENV['CURRENT_QUERY_HOURS'] || '336'
BASELINE_QUERY_HOURS = ENV['BASELINE_QUERY_HOURS'] || '720'

# Ensure log directories exist before supervisord starts.
# This is required because HOST_RESULT_DIR is bind-mounted and may be empty.
%w[
  logs
  logs/consumer
  logs/producer
  logs/api
  logs/commit-service
  logs/commit_time_service
].each do |subdir|
  FileUtils.mkdir_p("#{HOST_RESULT_DIR}/bisect/#{subdir}")
end

docker_rm 'bisect'

cmd = %w[
  docker run
  --name bisect
  --restart=always
  -itd
] + env + %W[
  -e LKP_SRC=#{DEFAULT_LKP}
  -e CCI_SRC=#{DEFAULT_CCI}
  -e MANTICORE_HOST=#{MANTICORE_HOST}
  -e BISECT_PRODUCER_ENABLED=true
  -e BISECT_CONSUMER_ENABLED=true
  -e BISECT_CONSUMER_STARTUP_DELAY_SECONDS=300
  -e FLASK_APP=#{FLASK_APP}
  -e LOG_LEVEL=DEBUG
  -e COMMIT_TIME_SERVICE_URL=http://localhost:8765
  -e BISECT_NOTIFICATION_WEBHOOK_URL=#{NOTIFICATION_WEBHOOK_URL}
  -e BISECT_FEISHU_WEBHOOK_URL=#{NOTIFICATION_FEISHU_WEBHOOK_URL}
  -e BISECT_FEISHU_SECRET=#{NOTIFICATION_FEISHU_SECRET}
  -e BISECT_NOTIFICATION_EMAIL=#{NOTIFICATION_EMAIL}
  -e BISECT_HEAD_VALIDATOR_ENABLED=#{HEAD_VALIDATOR_ENABLED}
  -e CURRENT_QUERY_HOURS=#{CURRENT_QUERY_HOURS}
  -e BASELINE_QUERY_HOURS=#{BASELINE_QUERY_HOURS}
  -e KERNEL_CI_CONFIG_DIR=#{BISECT_RESULT_DIR}bisect/kernel_ci_config
  -e BISECT_MAX_COMMIT_AGE_DAYS=365
  -e BISECT_THREADS=64
  -e WORK_DIR=#{BISECT_WORK_DIR}
  -e BISECT_COMMIT_QUERY_PRISTINE_BASE_DIR=#{BISECT_WORK_DIR}/bisect_repos/pristine_query
  -v #{HOST_WORK_DIR}:#{BISECT_WORK_DIR}
  -v #{HOST_RESULT_DIR}:#{BISECT_RESULT_DIR}
  -v #{HOST_RESULT_DIR}:#{HOST_RESULT_DIR}
  -v #{DEFAULT_CACHE}:#{DEFAULT_CACHE}
  -v #{KERNEL_CI_DIR}:#{KERNEL_CI_DIR}
  -v #{AUTO_TEST_REPOS_DIR}:#{AUTO_TEST_REPOS_DIR}
  -v #{DEFAULT_CONFIG_DIR}:#{DEFAULT_CONFIG_DIR}:ro
  -v #{DEFAULT_USER_CONFIG_DIR}:#{DEFAULT_BISECT_CONFIG_DIR}
  -v #{SUPERVISORD_CONF}:/etc/supervisor/supervisord.conf:ro
  -v /etc/localtime:/etc/localtime:ro
  -v /etc/compass-ci/register:/etc/compass-ci/register:ro
  -p 9999:9999
  -p 8765:8765
]

# 开发模式：映射宿主机代码目录，覆盖镜像内代码
if DEV_MODE
  puts "=== DEV MODE ==="
  puts "  CCI_SRC: #{HOST_CCI_SRC} -> #{DEFAULT_CCI}"
  puts "  LKP_SRC: #{HOST_LKP_SRC} -> #{DEFAULT_LKP}"

  cmd += %W[
    -v #{HOST_CCI_SRC}:#{DEFAULT_CCI}
    -v #{HOST_LKP_SRC}:#{DEFAULT_LKP}
  ]
end

cmd += ['bisect']
cmd += ['supervisord', '-c', '/etc/supervisor/supervisord.conf']

system(*cmd)
