#!/bin/sh
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

VERSION=v3.5.7
docker_skip_rebuild "etcd:alpine"

[ "$(arch)" == "aarch64" ] && ARCH=arm64
[ "$(arch)" == "x86_64" ] && ARCH=amd64

docker build --no-cache -t etcd:alpine --build-arg VERSION=${VERSION} --build-arg ARCH=${ARCH} .

push_image_remote "etcd:alpine"
