#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

docker_rm etcd-server

cmd=(
	docker run
	-d
	-p 2379:2379
	-p 2380:2380
	-p 4001:4001
	-p 7001:7001
	-v /srv/etcd/dir:/data
	-v /etc/localtime:/etc/localtime:ro
	-e ETCD_UNSUPPORTED_ARCH=arm64
	--name etcd-server
	etcd-v3.4.15:alpine
	--name node-1
	--data-dir /data
	--initial-cluster-state new
	--listen-client-urls http://0.0.0.0:2379
	--advertise-client-urls http://0.0.0.0:2379
)

"${cmd[@]}"
