#!/bin/sh
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_skip_rebuild "apline311:git-daemon"

docker build --no-cache -t apline311:git-daemon .

push_image_remote "apline311:git-daemon"
