#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

start_pod

docker_rm git-daemon

lkp=$(id -u lkp)

cmd=(
	docker run
	--restart=always
	--name git-daemon
	-u $lkp
	-d
	-p 9418:9418
	-v /srv/git:/git
	-v /etc/localtime:/etc/localtime:ro
	apline311:git-daemon
)

"${cmd[@]}"

# test

echo you can use git clone command: git clone git://127.0.0.1/\$project_name

