apiVersion: apps/v1
kind: Deployment
metadata:
  name: serial-logging
  namespace: ems1
spec:
  selector:
    matchLabels:
      app: serial-logging
  template:
    metadata:
      labels:
        app: serial-logging
    spec:
      nodeSelector:
        compass-ci.io/node-role: master
      initContainers:
      - name: check-dep
        image: k8s-start-check:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          python3 k8s_start_check.py es;
          python3 k8s_start_check.py rabbitmq
        env:
        - name: ES_HOST
          value: es
        - name: ES_PORT
          value: "9200"
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: secrets-env
              key: ES_USER
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-env
              key: ES_PASSWORD
        - name: MQ_HOST
          value: rabbitmq
        - name: MQ_PORT
          value: "5672"
      containers:
      - name: serial-logging
        image: serial-logging:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'umask 002 && ./serial-logging']
        envFrom:
        - configMapRef:
            name: pub-env
        - secretRef:
            name: secrets-env
        env:
        - name: CCI_SRC
          value: /c/cci
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          subPath: localtime
        - name: result
          mountPath: /srv/result
        resources:
          limits:
            memory: 15Gi
          requests:
            memory: 10Mi
        securityContext:
          runAsUser: 1090
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: localtime
        configMap:
          name: localtime
      - name: result
        hostPath:
          path: /srv/result
