#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

require 'set'
require_relative '../defconfig.rb'

names = Set.new %w[
  REDIS_PASSWORD
]

defaults = relevant_service_authentication(names)


docker_skip_rebuild "redis507n:alpine311"
system "docker build -t redis507n:alpine311 --build-arg PASSWD=#{defaults['REDIS_PASSWORD']} ."

push_image_remote "redis507n:alpine311"
