apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: ems1
spec:
  selector:
    app: etcd
  ports:
  - name: etcd-server
    port: 2380
  - name: etcd-client
    port: 2379
  - name: http
    port: 80
    targetPort: 2379
  publishNotReadyAddresses: true