apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-etcd-0
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    name: etcd-etcd-0
    namespace: ems1
  capacity:
    storage: 50Gi
  local:
    path: /srv/etcd/etcd-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: local-storage/etcd-0
          operator: In
          values:
          - "true"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pub-storageclass
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-etcd-1
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    name: etcd-etcd-1
    namespace: ems1
  capacity:
    storage: 50Gi
  local:
    path: /srv/etcd/etcd-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: local-storage/etcd-1
          operator: In
          values:
          - "true"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pub-storageclass
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-etcd-2
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    name: etcd-etcd-2
    namespace: ems1
  capacity:
    storage: 50Gi
  local:
    path: /srv/etcd/etcd-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: local-storage/etcd-2
          operator: In
          values:
          - "true"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pub-storageclass
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-etcd-0
  namespace: ems1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pub-storageclass
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-etcd-1
  namespace: ems1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pub-storageclass
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-etcd-2
  namespace: ems1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pub-storageclass
  resources:
    requests:
      storage: 50Gi