apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: ems1
spec:
  selector:
    app: webhook
  ports:
  - name: http
    port: 80
    targetPort: 20005
  - name: webhook
    port: 20005