#!/bin/bash
# Origin: https://hub.docker.com/r/netdata/netdata
# SPDX-License-Identifier: GPLv3+

cmd=(
	docker run -d 
	--name netdata 
	-p 19999:19999 
	-v /proc:/host/proc:ro 
	-v /sys:/host/sys:ro 
	-v /var/run/docker.sock:/var/run/docker.sock:ro 
	-v /srv/netdata:/var/cache/netdata
	--cap-add SYS_PTRACE 
	--security-opt apparmor=unconfined 
	netdata/netdata
)
"${cmd[@]}"
