#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# frozen_string_literal: true

require_relative '../lab.rb'

docker_rm "kibana"

cmd = %w[
  docker run
  --restart=always
  --name kibana
  -d
  --link logging-es:elasticsearch
  -p 11309:5601
  kibana:7.6.2
]

system(*cmd)
