#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

. $CCI_SRC/container/defconfig.sh

lsmod | grep -q "^cifs\s" || {
	sudo modprobe cifs
}

docker_rm samba

cmd=(
	docker run -dt
	-p 445:445
	-v /srv/os:/srv/os:ro
	-v /srv/os:/srv/os-rw
	-v /srv/initrd:/srv/initrd
	-v /srv/result:/srv/result
	--name samba
	--restart=always
	alpine/samba
)

"${cmd[@]}"
