#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

lsmod | grep -q "^cifs\s" || {
	sudo modprobe cifs
}

docker_rm samba

cmd=(
	docker run -dt
	-p 445:445
	-v /srv/os:/srv/os
	-v /etc/localtime:/etc/localtime:ro
	-v /srv/initrd:/srv/initrd
	-v /srv/result:/srv/result
	--name os-cifs
	--restart=always
	os-cifs
)

"${cmd[@]}"
