#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require_relative './docker/docker'

tbox_group = 'dc-1g'
hostname = "#{tbox_group}.#{ENV['USER']}-#{Process.pid}"
# specify which queues will be request, use "," to separate more than 2 values
queues = "#{tbox_group}~#{ENV['USER']}"

main(hostname, queues)
