#!/bin/sh
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_skip_rebuild "fraoustin/gitweb"

git clone https://github.com/fraoustin/gitweb  ./

docker build --no-cache -t fraoustin/gitweb .
