#!/usr/bin/env bash

[[ $CCI_SRC ]] || CCI_SRC=/c/cci

. $CCI_SRC/container/lab.sh

service_port=${TASKQUEUE_PORT:-3060}

if [[ ! -f "taskqueue" ]]; then
  $CCI_SRC/container/compile .
else
  echo -e "\n\033[34m- Info: using \033[31mexists\033[34m taskqueue -\033[0m\n"
fi

docker build -t taskqueue-alpine:v0.001-${service_port} .
