#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# frozen_string_literal: true

require 'set'
require_relative '../defconfig.rb'

names = Set.new %w[
  TASKQUEUE_PORT
  REDIS_HOST
  REDIS_PORT
]

defaults = relevant_defaults(names)
env = docker_env(defaults)

service_port = defaults['TASKQUEUE_PORT'] || '3060'
service_name = 'taskqueue'
service_image = "#{service_name}-alpine:v0.001-#{service_port}"

docker_rm "#{service_name}-#{service_port}"

cmd = %W[
  docker run
  --name #{service_name}-#{service_port}
  --restart=always
  -d
  -u 1090:1090
  -p #{service_port}:#{service_port}
]
cmd += env
cmd += %W[
  -v /etc/localtime:/etc/localtime:ro
  #{service_image}
]

cmd += ['sh', '-c', "umask 002 && ./#{service_name}"]

system(*cmd)
