#!/usr/bin/env ruby
# frozen_string_literal: true

CCI_SRC = ENV['CCI_SRC']

system 'docker rm -f fluentd'

cmd = %W[
  docker run
  --restart=always
  --name fluentd
  -d
  -u 1090:1090
  -p 24224:24224
  -p 24224:24224/udp
  -p 8888:8888
  -e FLUENTD_CONF=docker-fluentd.conf
  -v #{CCI_SRC}/container/fluentd/docker-fluentd.conf:/fluentd/etc/docker-fluentd.conf
  fluentd:alpine
]
cmd += ['sh', '-c', 'umask 002 & fluentd -c /fluentd/etc/docker-fluentd.conf']

system(*cmd)
