#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# frozen_string_literal: true

require_relative '../defconfig.rb'

docker_rm "fluentd"

cmd = %w[
  docker run
  --restart=always
  --name fluentd
  -v /etc/localtime:/etc/localtime:ro
  -v /srv/cci/serial/logs:/srv/cci/serial/logs:ro
  -v /srv/cci/serial/fluentd-pos:/srv/cci/serial/fluentd-pos
  -d
  -u 1090:1090
  -p 24224:24224/tcp
  -p 24224:24224/udp
  -e FLUENTD_CONF=docker-fluentd.conf
  --log-driver json-file
  --log-opt max-size=1g
  fluentd:alpine
]
cmd += ['sh', '-c', 'umask 002 & fluentd -c /fluentd/etc/docker-fluentd.conf']

system(*cmd)
