#!/bin/bash
# Origin: https://github.com/git-cloner/gitcache
# Copyright (C) 2019-2020  Eric D.little51
# SPDX-License-Identifier: GPL-3.0

. ../defconfig.sh

docker_skip_rebuild "gitcache"

docker build -t gitcache .
