#!/usr/bin/env bash
# SPDX-License-Identifier: MulanPSL-2.0+

if [ ! -f "known_auth_keys" ]; then
  echo "-----> ERROR: no testbox rsa public key file 'known_auth_keys' at currrent DIR"
  exit 1
fi
docker build -t ssh-r:0.001 .
