#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

docker_name=ssh_r

docker_rm ${docker_name}

cmd=(
  docker run
  --restart=always
  --name ${docker_name}
  -e GATEWAY_PORTS=true
  -e TCP_FORWARDING=true
  -d
  -p 21000-23999:21000-23999
  -p 5051:22
  -v /etc/localtime:/etc/localtime:ro
  -v /srv/pub/sshr/keys/:/etc/ssh/keys
  ssh-r:0.001
)

"${cmd[@]}"
