apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-mirror
  namespace: ems1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-mirror
  template:
    metadata:
      labels:
        app: git-mirror
    spec:
      nodeSelector:
        compass-ci.io/node-role: "master"
      initContainers:
      - name: check-dep
        image: k8s-start-check:latest
        imagePullPolicy: IfNotPresent
        command: 
        - sh
        - -c
        - |
          python3 k8s_start_check.py rabbitmq
          python3 k8s_start_check.py es
        env:
        - name: MQ_HOST
          value: rabbitmq
        - name: MQ_PORT
          value: "5672"
        - name: ES_HOST
          value: es
        - name: ES_PORT
          value: "9200"
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: secrets-env
              key: ES_USER
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-env
              key: ES_PASSWORD
      - name: init-dir
        image: git-mirror:latest
        imagePullPolicy: IfNotPresent
        command: 
        - sh
        - -c
        - |
          cp /home/lkp/.ssh-tmp/* /home/lkp/.ssh/;
          chown -R 1090:1090 /home/lkp/.ssh;
          chmod 600 /home/lkp/.ssh/*;

          chown -hR 1090:1099 /srv/git;
          chown -hR 1090:1099 /c/git-repos;

          [ -d "/c/git-repos/my_upstreams/.git" ] || {
            mkdir -p /c/git-repos/my_upstreams.git
            cd /c/git-repos/my_upstreams.git
            git init --bare .
            git clone /c/git-repos/my_upstreams.git /c/git-repos/my_upstreams
          }

          chown -hR 1090:1099 /c/git-repos/my_upstreams

          cd /c/git-repos/my_upstreams
          git config --global --add safe.directory /c/git-repos/my_upstreams
          git config user.email "git-mirror@localhost"
          git config user.name "git-mirror"
        volumeMounts:
        - name: git-repos
          mountPath: /c/git-repos
        - name: git
          mountPath: /srv/git
        - name: git-ssh-conf
          mountPath: /home/lkp/.ssh-tmp
        - name: lkp-ssh-dir
          mountPath: /home/lkp/.ssh
        securityContext:
          runAsUser: 0
      containers:
      - name: git-mirror
        image: git-mirror:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'umask 002 && ./git-mirror.rb']
        envFrom:
        - configMapRef:
            name: pub-env
        - secretRef:
            name: secrets-env
        env:
        - name: CCI_SRC
          value: /c/compass-ci
        - name: REPO_SRC
          value: /c/git-repos
        - name: MQ_HOST
          value: rabbitmq
        - name: MQ_PORT
          value: "5672"
        resources:
          limits:
            memory: 15Gi
          requests:
            memory: 10Mi
        securityContext:
          runAsUser: 1090
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
            add:
            - DAC_READ_SEARCH
        volumeMounts:
        - name: git-repos
          mountPath: /c/git-repos
        - name: git
          mountPath: /srv/git
        - name: localtime
          mountPath: /etc/localtime
          subPath: localtime
        - name: defaults
          mountPath: /etc/compass-ci/defaults
        - name: service-env
          mountPath: /etc/compass-ci/service
        - name: lkp-ssh-dir
          mountPath: /home/lkp/.ssh
      volumes:
      - name: localtime
        configMap:
          name: localtime
      - name: service-env
        configMap:
          name: service-env
      - name: defaults
        configMap:
          name: compass-ci-defaults
      - name: git-ssh-conf
        secret:
          secretName: git-ssh-conf
          defaultMode: 384
      - name: lkp-ssh-dir
        emptyDir: {}
      - name: git-repos
        hostPath:
          path: /c/git-repos
      - name: git
        hostPath:
          path: /srv/git
