apiVersion: v1
kind: Service
metadata:
  name: git-daemon
  namespace: ems1
spec:
  selector:
    app: git-daemon
  ports:
  - name: http
    port: 80
    targetPort: 9418
  - name: git-daemon
    port: 9418