#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require 'set'
require_relative '../defconfig'

names = Set.new %w[
  LOGGING_ES_USER
  LOGGING_ES_PASSWORD
]

defaults = relevant_service_authentication(names)

docker_skip_rebuild 'kibana:7.11.1'

BASE_IMAGE_DICT = {
  'aarch64' => 'jamesgarside/kibana:7.11.1',
  'x86_64' => 'kibana:7.11.1'
}.freeze

BASE_IMAGE = BASE_IMAGE_DICT[%x(arch).chomp]

system "docker build -t kibana:7.11.1 --build-arg BASE_IMAGE=#{BASE_IMAGE} --build-arg USER=#{defaults['LOGGING_ES_USER']} --build-arg PASSWORD=#{defaults['LOGGING_ES_PASSWORD']} ."
