#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

[[ $CCI_SRC ]] || CCI_SRC=/c/compass-ci

. $CCI_SRC/lib/check_public_network.sh

public_network_ok && {
	gem sources -r https://rubygems.org/ -a https://gems.ruby-china.com/
	gem install --no-user-install git activesupport rest-client cucumber json faye-websocket elasticsearch bunny
}

grep -q '^lkp:' /etc/passwd || useradd -u 1090 lkp
grep -q '^mailer:' /etc/passwd || useradd -u 1144 mailer
grep -q '^team:' /etc/group || groupadd team
grep -q '^committer:' /etc/group || groupadd -g 1999 committer

cat >> /etc/sysctl.conf <<EOF
net.ipv4.ip_forward=1
net.ipv6.bindv6only=1
vm.max_map_count=262144
net.ipv4.ip_local_port_range = 32000 65535
EOF

sysctl -p

cat >> /etc/modules-load.d/nfs <<EOF
nfs
nfsd
EOF

cat >> /etc/modules-load.d/cifs <<EOF
cifs
EOF

server_ip=$(ip route get 1.2.3.4 | awk '{print $7; exit}')

: ${DOCKER_REGISTRY_HOST:=$server_ip}
: ${DOCKER_REGISTRY_PORT:=5001}
cat > /etc/docker/daemon.json <<EOF
{
  "log-driver": "fluentd",
  "log-opts":{
    "fluentd-address": "localhost:24225",
    "fluentd-async-connect": "true",
    "tag": "{{.Name}}"
  },
  "registry-mirrors": [
    "http://hub-mirror.c.163.com",
    "http://docker.mirrors.ustc.edu.cn"
  ],
  "insecure-registries": ["$DOCKER_REGISTRY_HOST:$DOCKER_REGISTRY_PORT"]
}
EOF

sed -i '/^Environment=/a\TimeoutSec=0' /usr/lib/systemd/system/docker.service

systemctl daemon-reload
systemctl restart docker
systemctl start libvirtd
