#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

gem install git activesupport rest-client cucumber json faye-websocket

adduser -u 1090 lkp

cat >> /etc/sysctl.conf <<EOF
net.ipv4.ip_forward=1
vm.max_map_count=262144
EOF

sysctl -p

cat >> /etc/modules-load.d/nfs <<EOF
nfs
nfsd
EOF
