#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# export config info setup.yaml server_ip, my_email, my_name.

. $CCI_SRC/lib/log.sh

export_config_variables()
{
	[[ -n "$my_email" && -n "$my_name" ]] && return

	mkdir -p /etc/compass-ci/
	cp -a $CCI_SRC/sparrow/setup.yaml /etc/compass-ci/setup.yaml

	options=( server_ip my_name my_email )

	for option in ${options[@]}
	do
		export $option=$(awk -F ": " '/^'$option'/ {print $2}' /etc/compass-ci/setup.yaml)
	done
}

export_config_variables

[[ -n "$my_email" && -n "$my_name" ]] || {
	log_error "ENV \$my_email or \$my_name doesn't exist, please config $CCI_SRC/sparrow/setup.yaml"
	exit 1
}
