apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: ems1
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        local-storage/rabbitmq: "true"
      initContainers:
      - name: init
        image: rabbitmq:latest
        command:
        - sh
        - -c
        - |
          chown -hR 1090:1090 /var/lib/rabbitmq;
          chown -hR 1090:1090 /var/log/rabbitmq;
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
        - name: log
          mountPath: /var/log/rabbitmq
        securityContext:
          runAsUser: 0
      containers:
      - name: rabbitmq
        image: rabbitmq:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
        - containerPort: 15672
        livenessProbe:
          tcpSocket:
            port: 15672
          initialDelaySeconds: 6
          periodSeconds: 6
          timeoutSeconds: 10
          failureThreshold: 6
        resources:
          limits:
            memory: 15Gi
          requests:
            memory: 10Mi
        securityContext:
          runAsUser: 1090
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          subPath: localtime
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
        - name: log
          mountPath: /var/log/rabbitmq
      volumes:
      - name: localtime
        configMap:
          name: localtime
      - name: rabbitmq
        hostPath:
          path: /srv/rabbitmq
      - name: log
        hostPath:
          path: /srv/log/rabbitmp
