#!/bin/sh
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

load_cci_defaults

docker_skip_rebuild "node:webhook"

download_repo "cbs" "$git_branch_cbs"

docker build --no-cache -t node:webhook .

push_image_remote "node:webhook"
