#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require_relative '../defconfig.rb'

docker_rm "webhook"

cmd = %w[
  docker run
  --restart=always
  --name webhook
  -d
  -p 11301:11301
  node:webhook
]

cmd += ['sh', '-c', 'node webhook.js']
system(*cmd)
