#!/usr/bin/env ruby
# frozen_string_literal: true

DOCKER_LKP = '/c/lkp-tests'
DOCKER_CCI = '/c/crystal-ci'
system 'docker rm -f git-mirror'

cmd = %W[
  docker run
  --restart=always
  --name git-mirror
  -u 1090:1999
  -d
  -e LKP_SRC=#{DOCKER_LKP}
  -e CCI_SRC=#{DOCKER_CCI}
  -v #{ENV['LKP_SRC']}:#{DOCKER_LKP}
  -v #{ENV['CCI_SRC']}:#{DOCKER_CCI}
  -v /srv/git:/srv/git
  -w /c/crystal-ci/sbin
  alpine38:git-mirror
]

cmd += ['sh', '-c', 'umask 002 && ./git-mirror.rb']
system(*cmd)
