#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# frozen_string_literal: true

require 'bunny'
require 'json'
require 'yaml'

# receive message and auto submit job
class AutoSubmit
  def initialize
    connection = Bunny.new('amqp://172.17.0.1:5672')
    connection.start
    channel = connection.create_channel
    @queue = channel.queue('new_refs')
    @repo2job = YAML.load_file("#{$PROGRAM_NAME}.yaml")
  end

  def get_pkgbuild_repo(repo_array)
    pkgbuild_repo = nil
    repo_array.each do |repo|
      next unless repo =~ /-git$/

      pkgbuild_repo = "archlinux/#{repo}"
      break
    end
    return pkgbuild_repo
  end

  def submit(newrefs_info, cmd, git_repo, repo2job_key)
    jobfile = "#{ENV['LKP_SRC']}/jobs/#{@repo2job[repo2job_key]}"
    newrefs_info['new_refs']['heads'].each_value do |value|
      commit_date = `git -C /srv/git/#{git_repo}.git log  --format=%ct -1 #{value}`
      system("#{cmd} -s 'upstream_commit: #{value}' -s 'commit_date: #{commit_date}' #{jobfile}")
    end
  end

  def get_argvs(newrefs_info, cmd)
    if newrefs_info['pkgbuild_repo']
      pkgbuild_repo = get_pkgbuild_repo(newrefs_info['pkgbuild_repo'])
      return unless pkgbuild_repo

      repo2job_key = 'archlinux'
      cmd = "#{cmd} -s 'pkgbuild_repo: #{pkgbuild_repo}'"
    else
      return unless @repo2job[git_repo]

      repo2job_key = git_repo
    end
    [cmd, repo2job_key]
  end

  def submit_job(newrefs_info)
    git_repo = newrefs_info['git_repo']
    cmd = "#{ENV['LKP_SRC']}/sbin/submit -s 'upstream_repo: #{git_repo}'"

    cmd, repo2job_key = get_argvs(newrefs_info, cmd)
    return unless repo2job_key

    submit(newrefs_info, cmd, git_repo, repo2job_key)
  end

  def listen
    @queue.subscribe(block: true) do |_delivery, _properties, message|
      Thread.new do
        message_info = JSON.parse(message)
        submit_job(message_info)
      end
      sleep(0.1)
    end
  end
end

auto_submitter = AutoSubmit.new
auto_submitter.listen
