#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require 'bunny'
require 'json'
require 'yaml'
require 'set'
require_relative '../lib/config_account'

# receive message and auto submit job
class AutoSubmit
  def initialize
    connection = Bunny.new('amqp://172.17.0.1:5672')
    connection.start
    channel = connection.create_channel
    @queue = channel.queue('new_refs')
  end

  def get_pkgbuild_repo(repo_array)
    pkgbuild_repo = "archlinux/#{repo_array[0]}"
    repo_array.each do |repo|
      next unless repo =~ /(-git|linux)$/

      pkgbuild_repo = "archlinux/#{repo}"
      break
    end
    return pkgbuild_repo
  end

  def get_argvs(newrefs_info)
    git_repo = newrefs_info['git_repo']
    puts "git_repo : #{git_repo}"
    url = Array(newrefs_info['url'])[0]
    submit_argv = ["#{ENV['LKP_SRC']}/sbin/submit upstream_repo=#{git_repo} upstream_url=#{url}"]

    if newrefs_info['pkgbuild_repo']
      pkgbuild_repo = get_pkgbuild_repo(newrefs_info['pkgbuild_repo'])
      return unless pkgbuild_repo

      submit_argv.push("pkgbuild_repo=#{pkgbuild_repo}")
    end
    submit_argv
  end

  def submit_one_job(submit_argv, git_repo, belong, branch, commit_id)
    mirror_dir = "/srv/git/#{belong}/#{git_repo}.git"
    inactive_time = %x(git -C #{mirror_dir} log --pretty=format:"%cr" -1 #{commit_id})
    return if inactive_time =~ /(month|year)/

    real_argvs = Array.new(submit_argv)
    real_argvs.push("upstream_branch=#{branch}")
    real_argvs.push("upstream_commit=#{commit_id}")
    real_argvs.push("upstream_dir=#{belong}")
    tag = %x(git -C #{mirror_dir} tag --points-at #{commit_id})
    real_argvs.push("upstream_tag=#{tag}") unless tag.empty?

    system(real_argvs.join(' '))
  end

  def submit_specific_branch(submit_argv, newrefs_info, branches)
    branches.each do |branch_name|
      branch = "refs/heads/#{branch_name}"
      commit_id = newrefs_info['new_refs']['heads'][branch]
      next unless commit_id

      submit_one_job(submit_argv, newrefs_info['git_repo'], newrefs_info['belong'], branch_name, commit_id)
    end
  end

  def submit_non_specific(newrefs_info, submit_argv)
    newrefs_info['new_refs']['heads'].each do |branch, commit_id|
      branch = branch.delete_prefix('refs/heads/')
      submit_one_job(submit_argv, newrefs_info['git_repo'], newrefs_info['belong'], branch, commit_id)
    end
  end

  # Add support of different branch different job
  # newrefs_info['submit'] is like:
  # [
  #  { "command" => "submit command 1",
  #    "branches" => [ "master", "next", ... ]
  #  },
  #  ...,
  #  { "command" => "submit command n",
  #    "branches" => [ "branch_name_a", "branch_name_b", ... ]
  #  }
  # ]
  def submit_job(newrefs_info)
    submit_argv = get_argvs(newrefs_info)
    return unless submit_argv

    return unless newrefs_info['submit']

    newrefs_info['submit'].each do |element|
      argvs = Array.new(submit_argv)
      argvs.push(element['command'])
      if element['branches']
        submit_specific_branch(argvs, newrefs_info, element['branches'])
      else
        submit_non_specific(newrefs_info, argvs)
      end
    end
  end

  def listen
    @queue.subscribe(block: true) do |_delivery, _properties, message|
      Thread.new do
        message_info = JSON.parse(message)
        submit_job(message_info)
      end
      sleep(0.1)
    end
  end
end

config_yaml('auto-submit')

auto_submitter = AutoSubmit.new
auto_submitter.listen
