#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# frozen_string_literal: true

# Usage:
#       compare "group1_conditions" "group2_conditions" ...
# Eg:
#       compare "id=6000,6001" "id=7000,7001"
#       compare "os=debian" "os=centos" -c "suite=iperf"
#       compare "commit=a12d232e" "commit=b3bacc31"

require 'optparse'
require_relative '../lib/compare.rb'

common_conditions = nil

opt_parser = OptionParser.new do |opts|
  opts.banner = 'Usage: compare "group1_conditions" "group2_conditions" ... -c "common_conditions"'

  opts.separator ''
  opts.separator 'a conditions can be "id=100, ..." or "suite=iperf os=debian ..."'
  opts.separator ''
  opts.separator 'options:'

  opts.on('-c', '--common common_conditions', 'common conditions of all group_conditions') do |c|
    common_conditions = c
  end

  opts.on_tail('-h', '--help', 'show this message') do
    puts opts
    exit
  end
end

argv = if ARGV == []
         ['-h']
       else
         ARGV
       end
opt_parser.parse!(argv)

compare_matrices_list(argv, common_conditions)
