#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

load_cci_defaults

: ${DOCKER_REGISTRY_HOST:="127.0.0.1"}
: ${DOCKER_REGISTRY_PORT:=5001}

image_name=$1

local_repository()
{
	echo "pull image from local repository"
	docker pull $DOCKER_REGISTRY_HOST:$DOCKER_REGISTRY_PORT/$image_name && {
		docker tag $DOCKER_REGISTRY_HOST:$DOCKER_REGISTRY_PORT/$image_name $image_name
	}
}

docker_hub()
{
	echo "pull image from docker hub"
	docker pull $image_name
}

main()
{
	local_repository || docker_hub
}

main
