#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

load_cci_defaults

: ${DOCKER_REGISTRY_HOST:="127.0.0.1"}
: ${DOCKER_REGISTRY_PORT:=5001}

image_name=$1

local_repository()
{
	cmd="docker pull $DOCKER_REGISTRY_HOST:$DOCKER_REGISTRY_PORT/$image_name"
	echo "$cmd"
	$cmd 2> /dev/null && {
		docker tag $DOCKER_REGISTRY_HOST:$DOCKER_REGISTRY_PORT/$image_name $image_name
	}
}

docker_hub()
{
	cmd="docker pull $image_name"
	echo "$cmd"
	$cmd
}

main()
{
	# Check if the image already exists locally
	if docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "^$image_name$"; then
		echo "Docker image $image_name exists locally. Skipping pull."
	else
		local_repository || docker_hub
	fi
}

main
