#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require 'optparse'
require 'json'
require_relative '../lib/es_jobs'

def parse_argv
  items = {}
  ARGV.each do |item|
    key, value = item.split('=')
    if key && value
      value_list = value.split(',')
      items[key] = value_list.length > 1 ? value_list : value
    end
  end
  items
end

opt_refine = [-1]
opt_fields = []
opt_stats_filter = []
opt_parser = OptionParser.new do |opts|
  opts.banner = 'Usage: es-jobs [options] search_key1=val1[,val2..] ..'

  opts.separator 'search_key can be submit_id, group_id'
  opts.separator 'Like es-jobs submit_id=xxx'
end

opt_parser.parse!(ARGV)
items = parse_argv

if items.empty?
  puts(opt_parser)
  exit
end

es_jobs = ESJobs.new(items, opt_refine, opt_fields, opt_stats_filter)
es_jobs.generate_result
es_jobs.output
