#!/bin/bash

info_file=$1

# when redo the email configration, delete the old config files
rm $HOME/.muttrc
rm $HOME/.mutt/local.muttrc
rm $HOME/.procmailrc
rm $HOME/.fetchmailrc

[[ -n $info_file ]] || {
        echo "add info_file for email config"
        exit 1
}

source $info_file

[[ -d ${MAIL_DIR}/${MAIL_BOX} ]] || {

        mkdir -p ${MAIL_DIR}/${MAIL_BOX}/new
        mkdir -p ${MAIL_DIR}/${MAIL_BOX}/cur
        mkdir -p ${MAIL_DIR}/${MAIL_BOX}/tmp
}

[[ -d ${MAIL_DIR}/log ]] || {
        mkdir -p ${MAIL_DIR}/log
}


# add config for procmail
cat >> $HOME/.procmailrc <<-EOF
	VERBOSE=off
	MAILDIR=${MAIL_DIR}
	DEFAULT=${MAIL_DIR}/${MAIL_BOX}
	LOGFILE=${MAIL_DIR}/log/procmail

	:0:
	${MAIL_BOX}/
EOF

# add config for fetchmail
cat >> $HOME/.fetchmailrc <<-EOF
	poll imap.exmail.qq.com with proto IMAP
	username "${EMAIL_ADDR}"
	password "${EMAIL_PASS}"
	mda "/usr/bin/procmail -f %F -d %T"
	nokeep
EOF

# add config for mutt
cat >> $HOME/.mutt/local.muttrc <<-EOF
	set ssl_starttls=yes
	set ssl_force_tls=yes
	set ssl_use_sslv3=yes
	set timeout=60
	set smtp_authenticators="login"
	set realname="${EMAIL_NAME}"
	set from="${EMAIL_ADDR}"
	set smtp_url="${EMAIL_SMTP_URL}"
	set smtp_pass="${EMAIL_PASS}"

	set mbox_type=Maildir
	set folder="~/Maildir"
	set mbox="~/Maildir/.tencent"
	set spoolfile="~/Maildir/.tencent"

	source /etc/mutt/aliases.muttrc.cf
EOF

chmod 700 $HOME/.fetchmailrc $HOME/.procmailrc

# start fetchmail process immediately.
ps -ef | grep fetchmail | grep -v grep | grep $USER | awk '{print $2}' | xargs kill -9
fetchmail -d 60

# add crontab jobs to start fetchmail at server's per reboot for users.
( crontab -l | grep -v "@reboot fetchmail -d 60"; echo "@reboot fetchmail -d 60" ) | crontab -
