#!/usr/bin/env ruby
# SPDX-License-Identifier: GPL-2.0-only

# frozen_string_literal: true

CCI_SRC = File.dirname(__dir__)

require 'optparse'
require "#{CCI_SRC}/lib/matrix2"

File.umask 0o002

def extract_stats(result_root)
  ENV['RESULT_ROOT'] = result_root
  job_script = result_root + '/job.sh'

  system job_script, 'extract_stats'
end

opt_parser = OptionParser.new do |opts|
  opts.banner = 'Usage: result2stats result_root'
  opts.separator 'eg: result2stats /srv/result/iperf/vm-1p1g/2020-09-30/crystal.91198'
  opts.separator ''
  opts.separator 'options:'

  opts.on_tail('-h', '--help', 'show this message') do
    puts opts
    exit
  end
end

argv = if ARGV == []
         ['-h']
       else
         ARGV
       end

opt_parser.parse!(argv)

result_root = argv[0] || ENV['RESULT_ROOT']
extract_stats result_root
create_stats result_root
