#!/bin/bash -e
# SPDX-License-Identifier: MulanPSL-2.0+
#
# config file locations can be:
# - /etc/compass-ci/defaults/scan.list
# - {HOME}/.config/compass-ci/defaults/scan.list
# - {PWD}/scan.list
#
# config file demo: # namp param: -iL
#   1.2.3.4
#   1.2.3.4/5

log_info()
{
	echo "$(date "+%Y%m%d %H%M%S ")[INFO] $*"
}

pre_works()
{
	log_info "Starting pre work ..."
}

nmap_scan()
{
	log_info "Starting nmap scan ..."
}

format_result()
{
	log_info "Starting format result ..."
}

post_works()
{
	log_info "Starting post work ..."

	log_info "Scan finished."
}

main()
{
	pre_works

	nmap_scan

	format_result

	post_works
}

main
