[supervisord]
nodaemon=true
user=bisect
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=info

[program:commit-time-service]
command=python3 /c/compass-ci/container/bisect/services/commit_time_service/server.py --host 0.0.0.0 --port 8765 --cache-size 10000
directory=/c/bisect
user=bisect
autostart=true
autorestart=true
stdout_logfile=/result/bisect/logs/commit-time-service.log
stderr_logfile=/result/bisect/logs/commit-time-service-error.log
environment=CCI_SRC="/c/compass-ci",WORK_DIR="/c/bisect",LKP_SRC="/c/lkp-tests"

[program:flask-api]
command=flask run --host=0.0.0.0 --port=9999
directory=/c/bisect
user=bisect
autostart=true
autorestart=true
stdout_logfile=/result/bisect/logs/bisect-api.log
stderr_logfile=/result/bisect/logs/bisect-api-error.log
environment=FLASK_APP="/c/compass-ci/container/bisect/app/__init__.py",CCI_SRC="/c/compass-ci",WORK_DIR="/c/bisect",LKP_SRC="/c/lkp-tests"
