#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require_relative '../defconfig.rb'

docker_skip_rebuild "es:7.11.1"

available_memory = get_available_memory

system "docker build -t es:7.11.1 --build-arg MEMORY=#{available_memory} --network=host ."
