apiVersion: v1
kind: Service
metadata:
  name: web-backend
  namespace: ems1
spec:
  selector:
    app: web-backend
  ports:
  - name: http
    port: 80
    targetPort: 10002
  - name: web-backend
    port: 10002