#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require_relative '../defconfig'

docker_skip_rebuild 'fluentd-base:alpine'

system 'docker build -t fluentd-base:alpine .'
