#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

cmd=(
	docker run 
	--restart=always
	-v debian-home:/home
	-v debian-root:/root
	-v /c:/c
	-v /srv/os:/srv/os
	-p 2201:2201
	-p 1301:1301
	--hostname debian
	--security-opt seccomp=unconfined
	-d
	debian:testbed
	/usr/sbin/sshd -D -p 2201
)

"${cmd[@]}"
