#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

ipmitool -N 5 -I lanplus -H $1 -U "$IPMI_USER" -E sol deactivate
sleep 3s
ipmitool -N 5 -I lanplus -H $1 -U "$IPMI_USER" -E sol activate
