#!/bin/bash -e
# For your reference only.
# It's better to run the below scripts step by step.

[[ $CCI_SRC ]] || export CCI_SRC=$(cd $(dirname $(realpath $0)); git rev-parse --show-toplevel)
cd $CCI_SRC/sparrow || exit

0-package/install
1-storage/tiny
1-storage/permission
2-network/br0
2-network/iptables
2-network/nfs
3-code/git
3-code/dev-env
4-docker/buildall
5-build/ipxe
6-test/qemu
6-test/docker
7-systemd/systemd-setup
