#!/bin/sh
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

load_cci_defaults

docker_skip_rebuild "alpine:auto-submit"

download_repo "cbs" "$git_branch_cbs"
download_repo "lkp-tests" "$git_branch_lkp"

docker build --no-cache -t alpine:auto-submit .

push_image_remote "alpine:auto-submit"