#!/bin/sh

cmd=(
	docker run
	--restart=always
	-u nobody
	-d
	-p 8100:8100
	-v /srv/git:/srv/git
	debian:remote-git
)

"${cmd[@]}"

cat <<EOF
you can use cmd:
curl -H 'Content-Type: Application/json' -XPOST 'localhost:8100/git_command' -d '{"git_repo": "crystal-ci/crystal-ci.git", "git_command": ["git-show", "HEAD"]}'
EOF
