#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

DIR=$(dirname $(realpath $0))
. $(dirname $DIR)/lab.sh

load_cci_defaults

cmd=(
	docker run
	--rm
	-e LKP_SRC=$LKP_SRC
	-v $LKP_SRC:$LKP_SRC
	-v $DIR/bin:/root/bin
	-v /srv/initrd/lkp/${lkp_initrd_user:-latest}:/osimage/user/lkp
	alpine:lkp
	/root/bin/pack-lkp.sh
)

"${cmd[@]}"
echo "PATH: /srv/initrd/lkp/${lkp_initrd_user:-latest}/lkp-aarch64.cgz"
