# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

FROM nginx:alpine

MAINTAINER Lu Weitao <luweitaobe@163.com>

COPY nginx.conf /etc/nginx/
