#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+


[[ $CCI_SRC ]] || CCI_SRC=/c/compass-ci

. $CCI_SRC/container/defconfig.sh
docker_rm web-backend-nginx

cmd=(
	docker run
	--name web-backend-nginx
	-p 20003:20003
	-p 20019:20019
	-p 20020:20020
	-d

	-v /etc/ssl/certs:/opt/cert

	--log-opt mode=non-blocking
	--log-opt max-buffer-size=4m

	web-backend-nginx
)

"${cmd[@]}"
