#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_skip_rebuild "rabbitmq:3-management"

docker pull rabbitmq:3-management

push_image_remote "rabbitmq:3-management"
