#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

start_pod

docker_name=rabbitmq

docker_rm $docker_name

cmd=(
	docker run
	--restart=always
	-d
	--name $docker_name
	--hostname $docker_name
	-u 1090
	-p 5672:5672
	-p 15672:15672
	-v /etc/localtime:/etc/localtime:ro
	-v /srv/rabbitmq:/var/lib/rabbitmq
	rabbitmq:3-management
)

"${cmd[@]}"

