#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

docker rm -f rabbitmq

cmd=(
	docker run
	--restart=always
	-d
	--name rabbitmq
	-p 5672:5672
	-p 15672:15672
	rabbitmq:3-management
)

"${cmd[@]}"

