#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

. $CCI_SRC/container/lab.sh

docker_rm rabbitmq
docker pull rabbitmq:3-management

cmd=(
	docker run
	--restart=always
	-d
	--name rabbitmq
	-p 5672:5672
	-p 15672:15672
	rabbitmq:3-management
)

"${cmd[@]}"

