#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

set -e

CURRENT_PATH=$(dirname `readlink -f $0`)
PROJECT_PATH=$(dirname $(dirname $CURRENT_PATH))

if [ -e "$CURRENT_PATH/lifecycle" ]; then
	rm -rf $CURRENT_PATH/lifecycle
fi

$PROJECT_PATH/container/compile .
