#! /bin/bash

dirs=(
	/srv/es
	/srv/es/logging-es
	/srv/cache/netdata_cache
	/srv/cache/netdata_lib
	/srv/git
	/srv/initrd
	/srv/initrd/pkg
	/srv/initrd/deps
	/srv/os
	/srv/redis
	/srv/result
	/srv/cci/scheduler
	/tftpboot
	/c
)

mkdir -p "${dirs[@]}"
