#! /bin/bash

dirs=(
	/srv/es
	/srv/es/logging-es
	/srv/cache/netdata_cache
	/srv/cache/netdata_lib
	/srv/cache/gitcache
	/srv/git
	/srv/initrd
	/srv/initrd/pkg
	/srv/initrd/deps
	/srv/os
	/srv/dc
	/srv/redis
	/srv/result
	/srv/cci/scheduler
	/srv/cci/serial/logs
	/srv/cci/serial/fluentd-pos
	/srv/cci/libvirt-xml
	/tftpboot
	/c
	/c/git-repos
	/etc/qemu
	/srv/cci/Maildir/.compass-ci/new
	/srv/cci/Maildir/.compass-ci/cur
	/srv/cci/Maildir/.compass-ci/sent
	/srv/rabbitmq
	/srv/tmp/public
)

mkdir -p "${dirs[@]}"
