#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_skip_rebuild "dnsmasq:alpine"

[[ -e /tftpboot/boot.ipxe ]] || {
    cp -a tftpboot/boot.ipxe /tftpboot/boot.ipxe
}

docker build -t dnsmasq:alpine .
