#!/bin/bash

[ -n "$(docker ps -a -q -f name='^dnsmasq$')" ] &&
docker rm -f dnsmasq

cmd=(
	docker run
	--restart=always
	--cap-add NET_ADMIN
	--net=host
	--publish 67:67/udp
	--publish 69:69/udp
	-v $PWD/dnsmasq.d:/etc/dnsmasq.d
	-v /tftpboot:/tftpboot:ro
	--detach
	--name dnsmasq
	dnsmasq:alpine
	dnsmasq -k
)

"${cmd[@]}"
