#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

. $CCI_SRC/container/lab.sh

docker_rm dnsmasq

ps -ef| grep dnsmasq| grep -v "grep"| awk '{print $2}'| xargs kill

cmd=(
	docker run
	--restart=always
	--cap-add NET_ADMIN
	--net=host
	--publish 67:67/udp
	--publish 69:69/udp
	-v $PWD/dnsmasq.d:/etc/dnsmasq.d
	-v /tftpboot:/tftpboot:ro
	--detach
	--name dnsmasq
	dnsmasq:alpine
	dnsmasq -k
)

"${cmd[@]}"
