#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# frozen_string_literal: true

require 'set'
require_relative '../lab.rb'

names = Set.new ['MONITOR_PORT']
defaults = relevant_defaults(names)

MONITOR_PORT = (defaults['MONITOR_PORT'] || '11310')

CCI_SRC = ENV['CCI_SRC']
system "bash #{CCI_SRC}/container/compile ."
system "docker build -t monitoring-#{MONITOR_PORT} ."

system 'rm monitoring'
