#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

if [ -d "./h5ai" ]; then
	rm -rf ./h5ai
fi
git clone https://gitee.com/luweitao_y/h5ai.git

docker_skip_rebuild "srv-http"

docker build -t srv-http .

rm -rf ./h5ai
