#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh
docker_rm srv-http-git

cmd=(
	docker run
	--restart=always
	--name srv-http-git
	-p 11305:11300
	-v /srv/git/archlinux:/srv/git/archlinux:ro
	-v /etc/localtime:/etc/localtime:ro
	-d
	srv-http
)

"${cmd[@]}"
