#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh
. ./docker_run.sh
docker_rm srv-http-rpm

cmd=(
	docker run
	--restart=always
	--name srv-http-rpm
	-e LISTEN_PORT=20012
	-p 20012:20012
	-v /srv/rpm/pub:/srv/rpm/pub:ro
	-v /etc/localtime:/etc/localtime:ro
	$(mount_ssl)
	-d
	srv-http
)

"${cmd[@]}"
