#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh
. ./docker_run.sh
docker_rm srv-http-cci

cmd=(
	docker run
	--restart=always
	--name srv-http-cci
	-e LISTEN_PORT=20011
	-p 20011:20011
	-v /srv/cci/libvirt-xml:/srv/cci/libvirt-xml:ro
	-v /srv/cci/profile:/srv/cci/profile:ro
	-v /etc/localtime:/etc/localtime:ro
	$(mount_ssl)
	-d
	srv-http
)

"${cmd[@]}"
