#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh
docker_rm srv-http-initrd

cmd=(
	docker run
	--restart=always
	--name srv-http-initrd
	-p 11303:11300
	-v /srv/initrd/qemu-image:/srv/initrd/qemu-image:ro
	-v /srv/initrd/dockerimage:/srv/initrd/dockerimage:ro
	-v /etc/localtime:/etc/localtime:ro
	-d
	srv-http
)

"${cmd[@]}"
