#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh
. ./docker_run.sh
docker_rm srv-http-os

cmd=(
	docker run
	--restart=always
	--name srv-http-os
	-e LISTEN_PORT=20009
	-p 20009:20009
	-v /srv/os:/srv/os:ro
	-v /etc/localtime:/etc/localtime:ro
	$(mount_ssl)
	-d
	srv-http
)

"${cmd[@]}"
