#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh
. ./docker_run.sh
docker_rm srv-http-pub

cmd=(
	docker run
	--restart=always
	--name srv-http-pub
	-e LISTEN_PORT=20006
	-p 20006:20006
	-v /srv/pub:/srv/pub:ro
	-v /etc/localtime:/etc/localtime:ro
	$(mount_ssl)
	-d
	srv-http
)

"${cmd[@]}"
