#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

start_pod

./start-pub
./start-result
./start-initrd
./start-os
./start-git
./start-rpm
./start-cci
./start-repositories
