#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh
docker_rm srv-http-cci

cmd=(
	docker run
	--restart=always
	--name srv-http-cci
	-p 11306:11300
	-v /srv/cci/libvirt-xml:/srv/cci/libvirt-xml:ro
	-v /etc/localtime:/etc/localtime:ro
	-d
	srv-http
)

"${cmd[@]}"
