#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

. ../lab.sh

docker_rm rsync_server
cmd=(
	docker run 
	-id
	--name=rsync_server 
	-v /srv/result:/result
	-p 873:873
	rsync_server:latest
)

"${cmd[@]}"
