#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_rm rsync_server
cmd=(
	docker run 
	-id
	--restart=always
	--name=rsync_server 
	-v /srv/result/upload:/srv/result/upload
	-v /srv/os/install/ks:/srv/os/install/ks
	-v /etc/localtime:/etc/localtime:ro
	-p 20004:11387
	rsync_server:latest
)

"${cmd[@]}"
