#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

[[ $CCI_SRC ]] || CCI_SRC=/c/compass-ci
[[ $LKP_SRC ]] || LKP_SRC=/c/lkp-tests

. $CCI_SRC/lib/check_public_network.sh

public_network_ok && $CCI_SRC/sbin/download-rootfs

tag=$(git -C $LKP_SRC tag | tail -n 1)
echo "y/n" | sh $CCI_SRC/container/lkp-initrd/run $tag
chown -R lkp:lkp /srv/upload-files
