#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

[[ $CCI_SRC ]] || CCI_SRC=/c/compass-ci

. $CCI_SRC/lib/check_public_network.sh

public_network_ok && $CCI_SRC/sbin/download-rootfs

sh $CCI_SRC/container/lkp-initrd/run $lab-v1.0
