apiVersion: v1
kind: Service
metadata:
  name: es
  namespace: ems1
spec:
  publishNotReadyAddresses: true
  selector:
    app: es
  ports:
  - name: http
    port: 80
    targetPort: 9200
  - name: db
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP