#!/usr/bin/env bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

load_service_config

cat > $CCI_SRC/container/dnsmasq/dnsmasq.d/${lab}.conf <<EOF
interface=$interface
dhcp-authoritative
dhcp-range=$dhcp_range
dhcp-option=$dhcp_option
EOF

cat > $CCI_SRC/container/dnsmasq/dnsmasq.d/multi-node.conf <<EOF
interface=$br1_interface
dhcp-authoritative
dhcp-range=$br1_dhcp_range
dhcp-option=$br1_ignore_dhcp_option
dhcp-option=$br1_dhcp_option
EOF
