#!/usr/bin/env bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

load_service_config

cat > $CCI_SRC/container/dnsmasq/dnsmasq.d/${lab}.conf <<EOF
interface=$interface
dhcp-authoritative
dhcp-range=$dhcp_range
EOF

SCHED_HOST=$(awk '/^SCHED_HOST:\s/ {print $2;exit}' /etc/compass-ci/defaults/*.yaml)
sed -i "s%172.17.0.1%${SCHED_HOST}%g" /tftpboot/boot.ipxe

chmod 600 /etc/compass-ci/accounts/account_conf.yaml
cat > /etc/compass-ci/accounts/account_conf.yaml <<'EOF'
SMTP_ADDRESS: $SMTP_ADDRESS
SMTP_PORT: $SMTP_PORT
SMTP_DOMAIN: $SMTP_DOMAIN
ROBOT_EMAIL_ADDRESS: $ROBOT_EMAIL_ADDRESS
ROBOT_EMAIL_PASSWORD: $ROBOT_EMAIL_PASSWORD
EOF
