#!/usr/bin/env bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

server_name=$(hostname | cut -f1 -d.)
server_ip=$(ip route get 1.2.3.4 | awk '{print $7; exit}')
: ${sched_host:=$server_ip}
: ${sched_port:=3000}
: ${initrd_http_port:=8800}
: ${gitcache_host:=$server_ip}
: ${gitcache_port:=5000}
: ${MASTER_FLUENTD_HOST:=$server_ip}
: ${MASTER_FLUENTD_PORT:=24224}
: ${DOCKER_REGISTRY_HOST:=$server_ip}
: ${DOCKER_REGISTRY_PORT:=5001}

mkdir -p /etc/compass-ci/defaults
cat > /etc/compass-ci/defaults/$server_name.yaml <<EOF
SCHED_HOST: $sched_host
SCHED_PORT: $sched_port
OS_HTTP_HOST: $os_http_host
INITRD_HTTP_HOST: $initrd_http_host
INITRD_HTTP_PORT: $initrd_http_port
GITCACHE_HOST: $gitcache_host
GITCACHE_PORT: $gitcache_port
MASTER_FLUENTD_HOST: $MASTER_FLUENTD_HOST
MASTER_FLUENTD_PORT: $MASTER_FLUENTD_PORT
DOCKER_REGISTRY_HOST: $DOCKER_REGISTRY_HOST
DOCKER_REGISTRY_PORT: $DOCKER_REGISTRY_PORT
EOF

cat > /etc/profile.d/compass.sh <<'EOF'
export LKP_SRC=/c/lkp-tests
export CCI_SRC=/c/compass-ci
export REPO_SRC=/c/upstream-repos

export PATH="$PATH:$CCI_SRC/sbin:$LKP_SRC/sbin:$LKP_SRC/bin"
EOF

source /etc/os-release

. $(dirname ${BASH_SOURCE[0]})/os/${ID}
