#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

# fix files permissions cause container service start failed
umask 002

# download git trees

cd /c || exit

# git clone https://gitee.com/openeuler/compass-ci.git
# modify and manual run for now:
[ -d "compass-ci/.git" ] || {
	git clone https://gitee.com/wu_fengguang/compass-ci.git

	cd /c/compass-ci || exit
	[ -n "$compass_commit_id" ] && git reset --hard "$compass_commit_id"

	ln -s compass-ci /c/cci
}

[ -d "lkp-tests/.git" ] || {
	git clone https://gitee.com/wu_fengguang/lkp-tests.git

	cd /c/lkp-tests || exit
	[ -n "$lkp_commit_id" ] && git reset --hard "$lkp_commit_id"
}

[ -d "upstream-repos/.git" ] || {
	git clone https://gitee.com/wu_fengguang/upstream-repos.git

	cd /c/upstream-repos || exit
	[ -n "$upstream_commit_id" ] && git reset --hard "$upstream_commit_id"
}
