#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

CCI_SRC=$CCI_SRC
bash $CCI_SRC/container/compile .

docker build -t extract-stats .

rm extract-stats
