#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_skip_rebuild "extract-stats"

CCI_SRC=$CCI_SRC
bash $CCI_SRC/container/compile . || exit

docker build -t extract-stats .

rm extract-stats
