#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

set -e

CURRENT_ARCH=$(arch)
SUPPORTED_ARCH=( "aarch64" )

CURRENT_PATH=$(dirname `readlink -f $0`)
PROJECT_PATH=$(dirname $(dirname $(dirname `readlink -f $0`)))

CCI_IMAGE_URL=${CCI_IMAGE_URL:-"https://eulermaker.compass-ci.openeuler.openatom.cn/api/repositories/compass-ci/latest/"}

prepare_images() {
    local image_url="$CCI_IMAGE_URL/$CURRENT_ARCH/"
    echo $image_url
    curl -s "$image_url" | \
	    grep -o 'href="[^"]*\.tar\.gz"' | \
	    sed 's/href="//;s/"$//' | \
	    sed "s|^|$image_url|" > $CURRENT_PATH/filelist.txt

    local master_dir="$CURRENT_PATH/roles/master/images/files/$CURRENT_ARCH"
    wget --no-check-certificate -i $CURRENT_PATH/filelist.txt -P $master_dir
}

prepare_manifests() {
    local dst_dir="$CURRENT_PATH/roles/kubectl/manifests/files"
    mkdir -p $dst_dir && cp -rf $PROJECT_PATH/manifests $dst_dir/
}

pushd $CURRENT_PATH

for arch in "${SUPPORTED_ARCH[@]}"; do
    prepare_images
done

prepare_manifests
popd
