#!/usr/bin/env ruby
# frozen_string_literal: true

require 'set'
require '../lab.rb'

names = Set.new ['SCHED_PORT']
defaults = relevant_defaults(names)

SCHED_PORT = (defaults['SCHED_PORT'] || '3000')

CCI_SRC = ENV['CCI_SRC']
system "bash #{CCI_SRC}/src/build"
system "mv #{CCI_SRC}/src/m_scheduler ./scheduler"

system "docker build -t sch-ruby-a:v0.00d-#{SCHED_PORT} ."

system 'rm scheduler'
