#!/usr/bin/ruby
# frozen_string_literal: true

require 'set'
require '../lab.rb'

names = Set.new %w[
  SCHED_HOST
  SCHED_PORT
  REDIS_HOST
  REDIS_PORT
  ES_HOST
  ES_PORT
  OS_HTTP_HOST
  OS_HTTP_PORT
  INITRD_HTTP_HOST
  INITRD_HTTP_PORT
]

defaults = relevant_defaults(names)
env = docker_env(defaults)

LKP_SRC = '/c/lkp-tests'
SCHED_PORT = defaults['SCHED_PORT'] || '3000'
system "docker rm -f s001-alpine-#{SCHED_PORT}"

cmd = %W[
  docker run
  --name s001-alpine-#{SCHED_PORT}
  -d
  -u 1090:1090
  -p #{SCHED_PORT}:#{SCHED_PORT}
] + env + %W[
  -e LKP_SRC=#{LKP_SRC}
  -v #{ENV['LKP_SRC']}:#{LKP_SRC}
  -v /srv/cci/scheduler/alpine:/srv/cci/scheduler
  -v /etc/localtime:/etc/localtime:ro
  -v /srv/result:/result
  -v /srv/initrd:/srv/initrd
  sch-ruby-a:v0.00d-#{SCHED_PORT}
]

cmd += ['sh', '-c', 'umask 002 && ./scheduler']

system(*cmd)
