# /etc/compass-ci/scheduler/config.yaml

log_level: 0
admin_token: ""

skip_account_verification: true

should_read_es: false
should_write_es: false
should_read_manticore: true
should_write_manticore: true

lab_id: ""
sched_port: 3300

es_host: "172.17.0.1"
es_port: 9200
es_user: ""
es_password: ""

manticore_host: "172.17.0.1"
manticore_port: 9308

ipmi_user: ""
ipmi_password: ""
