# /etc/compass-ci/scheduler/config.yaml

log_level: 0
admin_token: ""

skip_account_verification: true

should_read_es: false
should_write_es: false
should_read_manticore: true
should_write_manticore: true

worker_id: 0 # set to different values for all scheduler workers to share the same database
cluster_size: 100 # shall be same for all workers

sched_port: 3300 # set to different values to run in same machine

es_host: "172.17.0.1"
es_port: 9200
es_user: ""
es_password: ""

manticore_host: "172.17.0.1"
manticore_port: 9308

ipmi_user: ""
ipmi_password: ""
