#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# frozen_string_literal: true

require 'set'
require_relative '../defconfig.rb'

names = Set.new %w[
  SCHED_HOST
  SCHED_PORT
  REDIS_HOST
  REDIS_PORT
  ES_HOST
  ES_PORT
  OS_HTTP_HOST
  OS_HTTP_PORT
  INITRD_HTTP_HOST
  INITRD_HTTP_PORT
  FLUENTD_HOST
  FLUENTD_PORT
]

defaults = relevant_defaults(names)
env = docker_env(defaults)

DEFAULT_LKP = '/c/lkp-tests'
DEFAULT_CCI = '/c/crystal-ci'
SCHED_PORT = defaults['SCHED_PORT'] || '3000'
FLUENTD_HOST = defaults['FLUENTD_HOST'] || 'localhost'
FLUENTD_PORT = defaults['FLUENTD_PORT'] || '24224'
docker_rm "s001-alpine-#{SCHED_PORT}"

cmd = %W[
  docker run
  --restart=always
  --name s001-alpine-#{SCHED_PORT}
  -d
  -u 1090:1090
  -p #{SCHED_PORT}:#{SCHED_PORT}
] + env + %W[
  -e LKP_SRC=#{DEFAULT_LKP}
  -e CCI_SRC=#{DEFAULT_CCI}
  -v #{ENV['LKP_SRC']}:#{DEFAULT_LKP}
  -v #{ENV['CCI_SRC']}:#{DEFAULT_CCI}
  -v /srv/cci/scheduler/alpine:/srv/cci/scheduler
  -v /etc/localtime:/etc/localtime:ro
  -v /srv/result:/result
  -v /srv/initrd:/srv/initrd
  --log-driver=fluentd
  --log-opt fluentd-address=#{FLUENTD_HOST}:#{FLUENTD_PORT}
  --log-opt mode=non-blocking
  --log-opt max-buffer-size=4m
  --log-opt tag=scheduler-#{SCHED_PORT}
  sch-ruby-a:v0.00d-#{SCHED_PORT}
]

cmd += ['sh', '-c', 'umask 002 && ./scheduler']

system(*cmd)
