apiVersion: v1
data:
  smb.conf: |
    # refer to https://lkml.org/lkml/2019/7/16/716 and https://lkml.org/lkml/2019/9/19/586
    [global]
       workgroup = MYGROUP
       server string = Samba Server
       map to guest = Bad User
       load printers = no
       printing = bsd
       printcap name = /dev/null
       disable spoolss = yes
       disable netbios = yes
       server role = standalone
       server services = -dns, -nbt
       smb ports = 445
       create mode = 0777
       directory mode = 0777
       guest only = yes
       guest ok = yes
       server min protocol = NT1
       unix extensions = yes
       mangled names = no

    [initrd]
       path = /srv/initrd/
       comment = initrd
       browseable = yes
       writable = yes
       public = yes
       force user = lkp
       force group = lkp

    [osimage]
       path = /srv/initrd/
       comment = osimage
       browseable = yes
       writable = yes
       public = yes
       force user = lkp
       force group = lkp
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: initrd-cifs-conf
  namespace: ems1
