#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2024 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

docker_skip_rebuild "git-proxy"

load_cci_defaults

if [ ! -d git-mirror-server.git ]; then
	git clone https://gitee.com/chengli132/git-mirror-server.git
fi

cd git-mirror-server && docker build -t git-proxy .

push_image git-proxy:latest

