# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

FROM fluentd-base:alpine

COPY --chown=1090:1090 docker-fluentd.conf /fluentd/etc/docker-fluentd.conf
