#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require 'set'
require_relative '../defconfig.rb'

names = Set.new %w[
  FLUENTD_SERVER_HOST
  FLUENTD_SERVER_PORT
]

defaults = relevant_defaults(names)
FLUENTD_SERVER_PORT = defaults['FLUENTD_SERVER_PORT'] || '24224'
raise 'must config FLUENTD_SERVER_HOST' unless defaults['FLUENTD_SERVER_HOST']

docker_rm 'sub-fluentd'

cmd = %W[
  docker run
  --restart=always
  --name sub-fluentd
  -v /etc/localtime:/etc/localtime:ro
  -v /srv/cci/serial/logs:/srv/cci/serial/logs:ro
  -v /srv/cci/serial/fluentd-pos:/srv/cci/serial/fluentd-pos
  -d
  -u 1090:1090
  -p 24224:24224/tcp
  -p 24224:24224/udp
  -e FLUENTD_CONF=docker-fluentd.conf
  -e FLUENTD_SERVER_HOST=#{defaults['FLUENTD_SERVER_HOST']}
  -e FLUENTD_SERVER_PORT=#{FLUENTD_SERVER_PORT}
  --log-driver json-file
  --log-opt max-size=1g
  sub-fluentd:alpine
]
cmd += ['sh', '-c', 'umask 002 & fluentd -c /fluentd/etc/docker-fluentd.conf']

system(*cmd)
