#!/bin/sh
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. ../defconfig.sh

load_service_authentication

docker_rm assign-account

cmd=(
	docker run
	--restart=always
	--name=assign-account
	-d
	-e ES_USER=$ES_USER
	-e ES_PASSWORD=$ES_PASSWORD
	-v /etc:/etc:rw
	-v /srv/account-info:/opt/account_data/:rw
	-v /home:/home:rw
	-p 10000:10000
	assign-account
)

"${cmd[@]}"
