#!/usr/bin/env bash
# SPDX-License-Identifier: MulanPSL-2.0+

SCHED_DEBUG_DIR=/c/cci/scheduler
DIR=$(dirname $(realpath $0))
[[ $LKP_SRC ]] || LKP_SRC=/c/lkp-tests
[[ $CCI_SRC ]] || CCI_SRC=/c/crystal-ci

if [ ! -d test ]; then
  mkdir test
fi

cmd=(
  docker run
  --rm
  -e LKP_SRC=/c/lkp-tests
  -e CCI_SRC=/c/crystal-ci
  -e REDIS_PORT=6380
  -e ES_PORT=9201
  -e CRYSTAL_PATH="lib:/usr/share/crystal/app/lib:/usr/lib/crystal/shards:/usr/lib/crystal/core:/c/lkp-tests/lib:$SCHED_DEBUG_DIR"
  -it
  -u $UID
  -v $DIR:$SCHED_DEBUG_DIR
  --mount type=tmpfs,destination=/result
  -v $LKP_SRC:/c/lkp-tests
  -v $CCI_SRC:/c/crystal-ci
  --mount type=tmpfs,destination=/initrd
  -w $SCHED_DEBUG_DIR
  alpine:scheduler-dev
  sh
)

"${cmd[@]}"

