../sbin/scheduler:
	crystal build -o ../sbin/scheduler scheduler.cr
../sbin/lifecycle:
	crystal build -o ../sbin/lifecycle lifecycle.cr
../sbin/watch-jobs:
	crystal build -o ../sbin/watch-jobs watch-jobs.cr
../sbin/monitoring:
	crystal build -o ../sbin/monitoring monitoring.cr
../sbin/extract-stats:
	crystal build -o ../sbin/extract-stats extract-stats.cr
../sbin/delimiter:
	crystal build -o ../sbin/delimiter delimiter.cr
../sbin/updaterepo:
	crystal build -o ../sbin/updaterepo updaterepo.cr
../sbin/serial-logging:
	crystal build -o ../sbin/serial-logging serial-logging.cr
../sbin/post-extract:
	crystal build -o ../sbin/post-extract post-extract.cr
