../sbin/scheduler:
	CRYSTAL_PATH="lib:." crystal build -o ../sbin/scheduler scheduler.cr
../sbin/lifecycle:
	CRYSTAL_PATH="lib:." crystal build -o ../sbin/lifecycle lifecycle.cr
../sbin/watch-jobs:
	CRYSTAL_PATH="lib:." crystal build -o ../sbin/watch-jobs watch-jobs.cr
../sbin/monitoring:
	CRYSTAL_PATH="lib:." crystal build -o ../sbin/monitoring monitoring.cr
../sbin/extract-stats:
	CRYSTAL_PATH="lib:." crystal build -o ../sbin/extract-stats extract-stats.cr
../sbin/delimiter:
	CRYSTAL_PATH="lib:." crystal build -o ../sbin/delimiter delimiter.cr
../sbin/extract-stats:
	CRYSTAL_PATH="lib:." crystal build -o ../sbin/extract-stats extract-stats.cr
../sbin/post-extract:
	CRYSTAL_PATH="lib:." crystal build -o ../sbin/post-extract post-extract.cr
