#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

. ../lab.sh

load_cci_defaults

cmd=(
	docker run
	--restart=always
#	--name initrd-http
	-p ${INITRD_HTTP_PORT:-8800}:80
	-v /srv/initrd:/usr/share/nginx/html/initrd:ro
	-d
	initrd-http
)

"${cmd[@]}"
