#!/bin/bash
# Origin: https://hub.docker.com/r/netdata/netdata
# SPDX-License-Identifier: GPL-3.0+

FROM netdata/netdata

MAINTAINER Xiao Shenwei <xiaoshenwei96@163.com>

RUN usermod -u 1090 netdata && \
    groupmod -g 1090 netdata
