apiVersion: v1
data:
  nginx.conf: |-
    worker_processes auto;

    error_log /var/log/nginx/error.log warn;

    pid /var/run/nginx.pid;

    worker_rlimit_nofile 4096;
    events {
      use epoll;
      worker_connections 4096;
    }

    http {
      resolver kube-dns.kube-system.svc.cluster.local;
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
      '$status $body_bytes_sent "$http_referer" '
      '"$http_user_agent" "$http_x_forwarded_for"';

      access_log /var/log/nginx/access.log main;

      autoindex off;
      sendfile on;

      keepalive_timeout 300;
      keepalive_requests 100;
      proxy_read_timeout 900;
      proxy_connect_timeout 60;

      proxy_send_timeout 60;
      client_header_timeout 60;
      client_header_buffer_size 1k;
      large_client_header_buffers 4 64k;
      client_body_buffer_size 16K;
      client_body_timeout 60;
      send_timeout 60;
      server_tokens off;
      port_in_redirect off;
      limit_conn_zone $binary_remote_addr zone=conn_zone:10m;
      limit_conn_zone $server_name zone=perserver:10m;
      limit_req_zone global zone=req_zone:1m rate=1000r/s;
      limit_req_zone $binary_remote_addr zone=event_zone:10m rate=20r/s;

      proxy_request_buffering off;
      client_max_body_size 50m;

      # add_header Content-Security-Policy upgrade-insecure-requests; # mix https + http access
      add_header X-Content-Type-Options nosniff;
      add_header X-XSS-Protection "1; mode=block";
      add_header Strict-Transport-Security "max-age=31536000";
      add_header Cache-Control no-store;
      add_header Pragma no-cache;
      add_header X-Frame-Options "SAMEORIGIN";
      add_header Content-Security-Policy "script-src 'self' 'unsafe-eval' *.baidu.com ers.baidu.com www.googletagmanager.com 'unsafe-inline';object-src 'none';frame-ancestors 'self'";

      proxy_hide_header X-Powered-By;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header REMOTE_ADDR $remote_addr;
      proxy_set_header REMOTE-HOST $remote_addr;
      server {
        set $web_backend web-backend.ems1.svc.cluster.local:10002;

        listen 30107;
        server_name localhost;
        charset utf-8;
        limit_conn perserver 50;
        if ($request_method = 'OPTIONS') {
          return 401;
        }

        location / {
            root   /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
            index  index.html;
        }

        location /web_backend/ {
            proxy_pass http://$web_backend;
        }

        location /api/ {
            proxy_pass https://api.openeuler.org/pkgmanagedebug/;
        }

        error_page 500 501 502 503 504 505 /500.html;
        error_page 401 /401.html;
        error_page 404 /404.html;

        location = /401.html {
          root /usr/share/nginx/html;
        }

        location = /404.html {
          root /usr/share/nginx/html;
        }

        location = /500.html {
          root /usr/share/nginx/html;
        }

        location ~ /\. {
          deny all;
          return 404;
        }
      }
    }

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: compass-ci-web
  namespace: ems1
