#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh

docker_rm logging-es

cmd=(
	docker run
	--restart=always
	-v /etc/localtime:/etc/localtime:ro
	-d
	-p 9202:9200
	-p 9302:9300
	-v /srv/es/logging-es:/srv/es/logging-es
	--name logging-es
	logging-es:7.6.2
)

"${cmd[@]}"

echo "Please wait 60s for setting index"
sleep 60

curl -H "Content-Type: application/json" -XPUT "localhost:9202/_settings" -d '
{
	"index": {
	"refresh_interval": "120s",
	"translog.durability": "async",
	"translog.sync_interval": "120s",
	"translog.flush_threshold_size": "1024mb"}
}'
