#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+

. $CCI_SRC/container/defconfig.sh

docker_rm logging-es

cmd=(
	docker run
	--restart=always
	-v /etc/localtime:/etc/localtime:ro
	-d
	-p 9202:9200
	-p 9302:9300
	-v /srv/es/logging-es:/srv/es/logging-es
	--name logging-es
	logging-es:7.6.2
)

"${cmd[@]}"
