#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require_relative '../defconfig.rb'

docker_rm "master-fluentd"

cmd = %w[
  docker run
  --restart=always
  --name master-fluentd
  -v /etc/localtime:/etc/localtime:ro
  -d
  -u 1090:1090
  -p 24225:24224/tcp
  -p 24225:24224/udp
  -e FLUENTD_CONF=docker-fluentd.conf
  --log-driver json-file
  --log-opt max-size=1g
  master-fluentd:alpine
]
cmd += ['sh', '-c', 'umask 002 & fluentd -c /fluentd/etc/docker-fluentd.conf']

system(*cmd)
