#!/usr/bin/env bash

CODE_DIR=/c/cci/src
COMPILE_DIR=/c/cci/compile

DIR=$(dirname $(realpath $0))

cmd=(
  docker run
  --rm
  -e CRYSTAL_PATH="lib:/usr/share/crystal/app/lib:/usr/lib/crystal/shards:/usr/lib/crystal/core:$CODE_DIR"
  -it
  -u $UID
  -v $CCI_SRC/src:$CODE_DIR
  -v $DIR:$COMPILE_DIR
  -w $COMPILE_DIR
  alpine:scheduler-dev
  sh -c "crystal build $CODE_DIR/taskqueue.cr -o taskqueue"
)

"${cmd[@]}"

