#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

cmd=(
	docker run
	--rm
	-v $PWD:/shellbox
	shellcheck
	shellcheck "$@"
)

"${cmd[@]}"

