#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.

. $CCI_SRC/container/defconfig.sh
. $LKP_SRC/lib/log.sh

lsmod | grep -q "^cifs\s" || {
	log_error "[ERROR] kernel module cifs is missing (try: sudo modprobe cifs)"
	exit 1
}

docker_rm initrd-cifs

cmd=(
	docker run
	-d
	-p 446:445
	-v /etc/localtime:/etc/localtime:ro
	-v /srv/initrd:/srv/initrd
	--name initrd-cifs
	--restart=always
	initrd-cifs
)

"${cmd[@]}"
